## Step 0: 데이터 로드하기

- 미션: 제공된 sensor_anomaly.csv 파일을 로드하여 data라는 변수에 NumPy 배열로 불러오세요.

- 배경
> "여러분은 공장 설비에서 1000초간 10개 센서로 측정한 데이터를 sensor_anomaly.csv 파일로 전달받았습니다. 이 데이터는 (1000, 10) 형태의 NumPy 배열입니다. 이 데이터에는 고장난 센서가 포함되어 있습니다. 데이터를 AI 모델에 입력하기 전  Numpy를 이용해서 몇 번 센서가 고장난 것인지 파악하고 해당 센서의 데이터는 삭제하고자 합니다."

In [1]:
import numpy as np
import pandas as pd

np.set_printoptions(precision=2, suppress=True) # 출력 옵션 설정
df = pd.read_csv("sensor_anomaly.csv")

print(f"\n원본 데이터 (처음 5행):")
display(df.head())
print(f"\n원본 데이터 (마지막 5행):")
display(df.tail())

data = df.to_numpy()

원본 데이터 (처음 5행):

,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,sensor_8,sensor_9,sensor_10
0,80.496714,3.486174,120.841995,0.576151,9.882923,54.578553,2.515843,91.304639,1.753053,30.813840
1,79.536582,3.453427,120.314551,0.404336,9.137541,53.987882,1.997434,90.534220,1.709198,27.881544
2,81.465649,3.477422,120.087787,0.428763,9.727809,55.199661,1.969801,90.638687,1.739936,29.562459
3,79.398293,3.685228,119.982454,0.447114,10.411272,52.802481,2.241773,86.668561,1.667181,30.295292
4,80.738467,3.517137,119.849657,0.484945,9.260739,53.704280,2.107872,91.797108,1.834362,27.355440

원본 데이터 (마지막 5행):

,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,sensor_8,sensor_9,sensor_10
995,80.867805,3.522741,118.843202,0.451961,10.127064,56.254692,2.278376,88.241183,1.865067,30.638866
996,78.929334,3.421568,120.895045,0.488275,10.794574,55.902033,2.102674,89.982650,1.806338,28.907415
997,79.087412,3.570139,121.098855,0.530189,10.757659,54.024808,2.534854,88.468434,1.698731,27.360062
998,79.554205,3.449628,120.683718,0.512195,9.403513,54.293093,2.125708,86.980830,1.701905,28.843780
999,81.433625,3.519145,120.860819,0.425068,10.597107,57.341984,1.800331,88.800962,1.849577,30.966583

## Step 1: 센서별 통계 계산 (Aggregation & axis)

먼저 각 센서(특성)가 어떤 분포를 갖는지 알아야 합니다. 1000개의 샘플 전체에 대해 각 센서별(열별) 평균과 표준편차를 계산합니다.

- 미션: data 배열을 이용해 10개 센서 각각의 평균(mean_per_sensor)과 표준편차(std_per_sensor)를 계산하세요.

- 핵심: axis를 0 또는 1로 지정해야 합니다.

In [2]:
# 여기 코드를 작성하세요.

# 1. 각 센서(열)의 평균 계산 (결과 shape: (10,))
mean_per_sensor = data.mean(axis=0)

# 2. 각 센서(열)의 표준편차 계산 (결과 shape: (10,))
std_per_sensor = data.std(axis=0)

print(f"\n--- Step 1: 통계 계산 ---")
print(f"센서별 평균 (shape: {mean_per_sensor.shape}):\n{mean_per_sensor}")
print(f"센서별 표준편차 (shape: {std_per_sensor.shape}):\n{std_per_sensor}")

--- Step 1: 통계 계산 ---
센서별 평균 (shape: (10,)):
[ 80.01   3.5  120.35   0.5   10.01  54.95   2.2   89.82   1.8   30.06]
센서별 표준편차 (shape: (10,)):
[ 1.    0.1  12.08  0.05  0.51  1.87  0.21  6.26  0.1   1.42]


## Step 2: Z-Score 정규화 (Broadcasting)

센서마다 스케일이 다릅니다 (e.g., 온도는 80, 압력은 3.5). AI 모델은 스케일에 민감하므로, 모든 센서 데이터를 평균 0, 표준편차 1을 갖도록 표준화(Z-score 정규화)합니다.

- 수식: Z=(X − μ)/σ​ (X: 원본 데이터, μ: 평균, σ: 표준편차)

- 미션: (1000, 10) 형태의 data 배열과 (10,) 형태의 mean_per_sensor, std_per_sensor를 이용해 정규화된 normalized_data를 만드세요.

- 핵심: for 루프 없이 단 한 줄의 코드로 10,000개의 데이터를 연산하는 NumPy의 브로드캐스팅을 활용합니다.

In [3]:
# 여기 코드를 작성하세요.

# Z-Score 정규화 (브로드캐스팅 활용)
# (1000, 10) - (10,) / (10,)
normalized_data = (data - mean_per_sensor) / std_per_sensor


# (검증) 정규화된 데이터의 평균은 0에, 표준편차는 1에 매우 가까워야 함
print(f"정규화 데이터의 평균 (0에 근사):\n", normalized_data.mean(axis=0))
print(f"정규화 데이터의 표준편차 (1에 근사):\n", normalized_data.std(axis=0))

정규화 데이터의 평균 (0에 근사):
 [-0.  0.  0. -0. -0. -0.  0. -0.  0.  0.]
정규화 데이터의 표준편차 (1에 근사):
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

## Step 3: 이상치 탐지 및 개수 확인 (Boolean Indexing)

정규화된 데이터(Z-score)에서 값이 +6 또는 -6을 벗어나면, 이는 통계적으로 '6-sigma'를 벗어나는 극단적인 이상치로 간주할 수 있습니다.

- 미션: normalized_data에서 절댓값이 6을 초과하는(즉, 6보다 크거나 -6보다 작은) 이상치가 총 몇 개인지 찾아내세요.

- 핵심: (조건)을 배열에 적용하는 불리언 인덱싱과 | (OR) 논리 연산자, np.sum()을 활용합니다.

- 고장으로 판단되는 센서는 몇번과 몇번입니까?
    - 힌트: 이상치가 존재하는 위치를 알기 위해 이상치가 표시된 어레이에 np.where()를 사용하세요. 아래 셀을 실행하여 np.where()가 어떻게 작동하는지 확인하세요. 아래 셀의 결과값은 값이 True인 행인덱스와 열인덱스입니다.

In [4]:
np.where([[True, False],
          [True, True]])

(array([0, 1, 1]), array([0, 0, 1]))

In [5]:
# 여기 코드를 작성하세요.

# 이상치 조건 마스크 생성 (True/False로 구성된 (1000, 10) 배열)
outlier_mask = (normalized_data > 6) | (normalized_data < -6)


# 이상치가 총 몇 개인지 확인 (True는 1, False는 0으로 계산됨)
num_outliers = np.sum(outlier_mask)


# 실제 이상치 값들만 출력해보기
outlier_values = normalized_data[outlier_mask]

# 고장난 센서 번호
print( outlier_mask.sum(axis=0) ) # 2번, 7번
rows, cols = np.where( outlier_mask )
print(cols)

[0 0 1 0 0 0 0 1 0 0]
[2 7]

## Step 4: 고장 센서 식별 및 데이터셋에서 제거

Step 3에서 찾은 "고장 센서" 정보를 바탕으로, 해당 센서의 열(column) 전체를 원본 data에서 제거하여 깨끗한 데이터셋 cleaned_data를 만드세요.

In [6]:
# 여기 코드를 작성하세요.
data[:, [0, 1, 3, 4, 5, 6, 8, 9]]

array([[80.5 ,  3.49,  0.58, ...,  2.52,  1.75, 30.81],
       [79.54,  3.45,  0.4 , ...,  2.  ,  1.71, 27.88],
       [81.47,  3.48,  0.43, ...,  1.97,  1.74, 29.56],
       ...,
       [79.09,  3.57,  0.53, ...,  2.53,  1.7 , 27.36],
       [79.55,  3.45,  0.51, ...,  2.13,  1.7 , 28.84],
       [81.43,  3.52,  0.43, ...,  1.8 ,  1.85, 30.97]], shape=(1000, 8))

In [7]:
np.delete(data, cols, axis=1)

array([[80.5 ,  3.49,  0.58, ...,  2.52,  1.75, 30.81],
       [79.54,  3.45,  0.4 , ...,  2.  ,  1.71, 27.88],
       [81.47,  3.48,  0.43, ...,  1.97,  1.74, 29.56],
       ...,
       [79.09,  3.57,  0.53, ...,  2.53,  1.7 , 27.36],
       [79.55,  3.45,  0.51, ...,  2.13,  1.7 , 28.84],
       [81.43,  3.52,  0.43, ...,  1.8 ,  1.85, 30.97]], shape=(1000, 8))